version: '3'

services:
  hub-main:
    build: ./mainHub
    container_name: hub-main
    volumes: 
      - ./mainHub:/mainHub
      - /mainHub/node_modules
    restart: always
    networks:
      - hub_network

  hub-serviceone: 
    build: ./serviceOne
    container_name: hub-serviceone
    volumes: 
      - ./serviceOne:/serviceOne
      - /serviceOne/node_modules
    restart: always
    networks:
      - hub_network

  nginx:
    restart: always
    build:
      context: ./nginx
    ports:
      - "80:80"   
    networks:
      - hub_network

networks:
  hub_network:
    driver: bridge
